#!/bin/bash
################################################################################
##
# @file setup
# @date 2016-01-13
# @author Tiago Lobato Gimenes    (tlgimenes@gmail.com)
#
# @copyright Tiago Lobato Gimenes 2015. All rights reserved.
#
# @license GNU Public License version 3
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# @brief
#
#
################################################################################
HELP="usage install path/to/machybris/tar path/to/arch/linux/rfs"

# Boolean values
TRUE=1
FALSE=0

MACHYBRIS_TAR=$1
MACHYBRIS_DIR=machybris

INSTALL_PATH=$2

SUPPORTED_EXTENSIONS="tgz"

################################################################################
is_extension_supported()
{
    extension=${MACHYBRIS_TAR##*.}

    for EXT in $SUPPORTED_EXTENSIONS
    do
        [ "$extension" == "$EXT" ] && echo $TRUE && exit
    done

    echo $FALSE
}

################################################################################
unpack_machybris()
{
    echo 'Unpacking machybris'

    # Create $MACHYBRIS_DIR
    [ -d $MACHYBRIS_DIR ] && rm -rf $MACHYBRIS_DIR; mkdir $MACHYBRIS_DIR

    # Unpack
    tar -zxf $MACHYBRIS_TAR -C $MACHYBRIS_DIR
}

################################################################################
copy_files_to_rfs()
{
    echo "Copying files to $INSTALL_PATH"

    sudo rsync --exclude=etc/init -abviuzP $MACHYBRIS_DIR/* $INSTALL_PATH 
    sync
}

################################################################################
# main()
if [ "$#" -ne "2" ]
then
    echo $HELP
elif [ "`is_extension_supported`" -ne "$TRUE" ]
then
    echo 'Extension not supported'
elif [ ! -d $INSTALL_PATH ]
then
    echo 'Install path does not exists'
elif [ ! -f "$1" ]
then
    echo "File $1 not found"
else
    unpack_machybris
    copy_files_to_rfs
fi

################################################################################

################################################################################
